import "../styles/globals.css";
import { MoralisProvider, useMoralis } from "react-moralis";
import Header from "../components/Header";
import Head from "next/head";
import { NotificationProvider } from "web3uikit";

const APP_ID = "m7lJMC0qSNO2fui1MNucgKWhGlRgBZ6MQuvSxiDc";
const SERVER_URL = "https://omlsaljbmwjd.usemoralis.com:2053/server";

function MyApp({ Component, pageProps }) {
    return (
        <div>
            <Head>
                <title>OpenOcean</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/logo.ico" />
            </Head>

            <MoralisProvider appId={APP_ID} serverUrl={SERVER_URL}>
                <NotificationProvider>
                    <Header />
                    <Component {...pageProps} />
                </NotificationProvider>
            </MoralisProvider>
        </div>
    );
}

export default MyApp;
