import "../styles/globals.css";
import { MoralisProvider, useMoralis } from "react-moralis";
import Header from "../components/Header";
import Head from "next/head";
import { NotificationProvider } from "web3uikit";
import { ApolloProvider, ApolloClient, InMemoryCache } from "@apollo/client";

const client = new ApolloClient({
    cache: new InMemoryCache(),
    uri: "https://api.studio.thegraph.com/query/29677/nft-marketplace/v0.0.1",
});

function MyApp({ Component, pageProps }) {
    return (
        <div>
            <Head>
                <title>OpenOcean</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/logo.ico" />
            </Head>

            <MoralisProvider initializeOnMount={false}>
                <ApolloProvider client={client}>
                    <NotificationProvider>
                        <Header />
                        <Component {...pageProps} />
                    </NotificationProvider>
                </ApolloProvider>
            </MoralisProvider>
        </div>
    );
}

export default MyApp;
